### ISSUE TITLE
issue with isAccountPasswordExpired

### ISSUE THREAD

**Issue by softal** [nordsoftware/yii2-account#1]
hi, nice extension.

there is a problem with the function isAccountPasswordExpired. it should choose one the last record (max (CreateDate)), and then compare passwordExpireTime. 
Now selects all those that are older than passwordExpireTime - - always display form to change password

![image](https://cloud.githubusercontent.com/assets/5954367/5288131/a58011b2-7b32-11e4-8440-26943bccc89e.png)

select within isAccountPasswordExpired returns:

<pre>
SELECT * FROM `account_password_history` 
WHERE (`accountId`=1) AND (UNIX_TIMESTAMP() - UNIX_TIMESTAMP(createdAt) > 56400) 
ORDER BY `createdAt` DESC
</pre>

![image](https://cloud.githubusercontent.com/assets/5954367/5288159/d1f09dac-7b32-11e4-8e7f-aa735b8bd732.png)

p.s. it would be nice to add captcha on login form when login attempts exeed the module parameter...

**Comment by cniska** [comment]
I think I fixed this issue already. Could you please try the latest version? Thanks.
