### ISSUE TITLE
Account creation cancelling via e-mail

### ISSUE THREAD

**Issue by antonkomarev** [nordsoftware/yii2-account#15]
If user has written not his\her email there should be link in recipients e-mail: **I haven't initiated a sign up** which should delete this account.
That feature needed for:
- accounts awaiting activation;
- active accounts but awaiting for email verification.

Maybe this feature could be useful in future for email changing or adding additional e-mail addresses to account, but it shouldn't delete account then, just remove\block generated token.

**Comment by hugovk** [comment]
Closing and archiving repo.
