### ISSUE TITLE
Attaching multiple e-mail addresses

### ISSUE THREAD

**Issue by antonkomarev** [nordsoftware/yii2-account#16]
This an addition to [Support for optional account verification](https://github.com/nordsoftware/yii2-account/issues/13).
Some services over internet (for example: Github, Trello) provide an ability to attach several e-mail addresses to account.
Trello even allow you to login before email verification, but got message on top of the website:
**Please confirm your email address: my@email.com. Resend email.**
![screenshot from 2015-02-28 19 12 40](https://cloud.githubusercontent.com/assets/1849174/6426841/1c3f6f34-bf7e-11e4-9629-ad8653491911.png)
And you got an ability to attach multiple email addresses and verify from any of them. I found it useful when one of my e-mail's ignored messages from Trello (they weren't even in spam folder).
It's very rare use case, and in most of cases could be just ignored, but interesting feature.

**Comment by hugovk** [comment]
Closing and archiving repo.
