### ISSUE TITLE
Social auth support

### ISSUE THREAD

**Issue by antonkomarev** [nordsoftware/yii2-account#6]
Is social registration/login planned in this module?

**Comment by antonkomarev** [comment]
Found it in `\nord\yii\account\widgets\AuthChoice` but there is no documentation how to use it.
Can you describe it more detailed, please?

I've added in `/config/main.php`:

``` php
'modules' => [
    'account' => [
        'class' => 'nord\yii\account\Module',
        'enableClientAuth' => true,
    ]
],
```

And in components section:

``` php
'components' => [
    'authClientCollection' => [
        'class' => 'yii\authclient\Collection',
        'clients' => [
            'google' => [
                'class' => 'yii\authclient\clients\GoogleOAuth',
                'clientId' => 'google_client_id',
                'clientSecret' => 'google_client_secret',
            ],
        ],
    ]
    ...
]
```

But is there any way to pass username\email in input fields on Connect screen (as done on packagist.org when you are connecting via GitHub account)?

**Comment by cniska** [comment]
That can be done after the client auth success callback is called, you can get that information from the provider. Did you sort out the URL issue? As for the widget you can use it as is and it basically supports the same interface as the widget from the auth client library.
